KaTreasureApp/urls.py
from django.urls import path
from KaTreasureApp import views, dashboard

app_name = 'KaTreasureApp'

urlpatterns = [
    # APP
    path('', views.base, name='base'),
    path('home', views.home, name='home'),
    path('availability', views.availability, name='availability'),
    path('create-room/', views.create_room, name='create-room'),
    path('book-room', views.book_room, name='book-room'),
    path('confirm-booking', views.confirm_booking, name='confirm-booking'),
    path('fetch-room-data/', views.fetch_room_data, name='fetch-room-data'),
    path('all-rooms/', views.all_rooms, name='all-rooms'),
    path('contactus', views.contactus, name='contactus'),

    # AUTH
    path('signin', views.login, name='login'),
    path('signup', views.signup, name='signup'),
    path('logout', views.logout, name='logout'),
    path('forgot_password', views.forgot_password, name='forgot_password'),
    
    # DASHBOARD
    path('dashboard/home', dashboard.home, name='dashboard'),
]

KaTreasureEH/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('KaTreasureApp.urls')),
    path('admin/', admin.site.urls),
]

templates/base/base-orig.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Ka Treasure Water Terraces Mountain Resort{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap" rel="stylesheet">
    {% block head %}

    {% endblock %}
</head>
<body>

    <header>
        <div class="navbar">
            <div class="logo">
                <a href="#">Ka Treasure</a>
            </div>
            <ul class="links">
                <li><a href="{% url 'KaTreasureApp:home' %}">Home</a></li>
                <li><a href="#">About Us</a></li>
                <li><a href="#">Services</a></li>
                <li><a href="#">Rooms</a></li>
                <li><a href="{% url 'KaTreasureApp:contactus' %}">Contact Us</a></li>
            </ul>
            <ul class="auth">
                {% if authenticated == True %}
                    <li><a href="#" class="name">{{full_name}}</a></li>
                    <li><a href="{% url 'KaTreasureApp:logout' %}" id="logout" class="action_btn">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'KaTreasureApp:login' %}" id="login" class="action_btn">Login</a></li>
                    <li><a href="{% url 'KaTreasureApp:signup' %}" id="signup" class="action_btn">Signup</a></li>
                {% endif %}
            </ul>
            <div class="toggle_btn">
                <i class="fa fa-bars"></i>
            </div>
        </div>
        <div class="dropdown_menu">
            <li><a href="#">{{full_name}}</a></li>
            <li><a href="{% url 'KaTreasureApp:home' %}">Home</a></li>
            <li><a href="#">About Us</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Rooms</a></li>
            <li><a href="{% url 'KaTreasureApp:contactus' %}">Contact Us</a></li>
            {% if authenticated == True %}
            <li><a href="{% url 'KaTreasureApp:logout' %}" class="action_btn">Logout</a></li>
            <style>
                .dropdown_menu.open {
                    height: 328px;
                }
            </style>
            {% else %}
            <style>
                .dropdown_menu.open {
                    height: 392px;
                }
            </style>
            <li><a href="{% url 'KaTreasureApp:login' %}" class="action_btn">Login</a></li>
            <li><a href="{% url 'KaTreasureApp:signup' %}" class="action_btn">Signup</a></li>
            {% endif %}
        </div>
    </header>
    <div id="messagemain" class="messagemain">

        {% include 'common/messages.html' %}
        
    </div>

    <main>
        <section id="hero">
            {% block content %}



            {% endblock %}
        </section>
    </main>
    <script type="text/javascript" src="{% static 'script.js' %}"></script>
    <script>
        function redirectToLogout() {
            window.location.href = "{% url 'KaTreasureApp:logout' %}";
        }
    </script>

</body>
</html>

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Ka Treasure Water Terraces Mountain Resort{% endblock %}</title>

    <!-- Favicon -->
    <link rel="icon" href="{% static 'img/logo.png' %}" type="image/x-icon">

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <!-- swiper js cdn link -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css" />
     <!-- custom css link -->
    {% block head %}

    {% endblock %}
</head>
<body>

    <!-- header -->
 
    <header class="header">
 
       <a href="#" class="logo"> <i class="fas fa-hotel"></i> hotel </a>
 
       <nav class="navbar">
          <a href="{% url 'KaTreasureApp:home' %}">home</a>
          <a href="#about">about</a>
          <a href="#room">room</a>
          <a href="#gallery">gallery</a>
          <a href="#review">review</a>
          <a href="#faq">faq</a>
          <a href="{% url 'KaTreasureApp:contactus' %}">contact us</a>
          <a href="#availability" class="btn"> book now</a>
          {% if authenticated == True %}
            <a href="{% url 'KaTreasureApp:logout' %}">Logout</a>
          {% else %}
            <a href="{% url 'KaTreasureApp:login' %}">Signin</a>
            <a href="{% url 'KaTreasureApp:signup' %}">Signup</a>
          {% endif %}
       </nav>
 
       <div id="menu-btn" class="fas fa-bars"></div>
 
    </header>
 
    <!-- end -->

    <div id="messagemain" class="messagemain">

        {% include 'common/messages.html' %}
        
    </div>

    {% block content %}



    {% endblock %}
    
    <script type="text/javascript" src="{% static 'script.js' %}"></script>
    <script>
        setTimeout(function() {document.getElementById('messagemain').innerHTML='';}, 5000);

        function redirectToLogout() {
            window.location.href = "{% url 'KaTreasureApp:logout' %}";
        }
    </script>

</body>
</html>